### ISSUE TITLE
国服6.1版本中使用Double Weaver插件

### ISSUE THREAD

**Issue by Jackcharled** [Bluefissure/DoubleWeaver#11]
https://raw.githubusercontent.com/Bluefissure/DalamudPlugins/Bluefissure/pluginmaster.json
库中显示的插件api为7版本 但是国服的卫月仅为api6版本 是否之后会解决这个问题 还是在国服未升级前将无法使用此插件

**Comment by Bluefissure** [comment]
https://raw.githubusercontent.com/Bluefissure/DalamudPlugins/Bluefissure/pluginmaster_api6.json
