### ISSUE TITLE
在Steam deck上安装失败

### ISSUE THREAD

**Issue by MasteRyuuuu** [Bluefissure/DoubleWeaver#12]
我使用国际服版本的启动器，可以在gamemode中启动国际服游戏并成功安装。国服无法通过steam启动，在使用steam deck的桌面模式启动国服后，安装时报错。确定安装了ping plugin，选择传统模式加载卫月框架。（另外想问一下xivlaunchercn是否会有像xivLauncher一样直接有一个steamdeck启动方法的教程。）

**Comment by Bluefissure** [comment]
请给 https://github.com/ottercorp/FFXIVQuickLauncher 提交 issue
