### ISSUE TITLE
Plugin cannot be loaded for Dalamund CN

### ISSUE THREAD

**Issue by zytadam** [Bluefissure/DoubleWeaver#14]
Is it banned by the Dalamund CN or just an update issue due to version 7.0? Thanks.

**Comment by Bluefissure** [comment]
please use pluginmaster_api9

**Comment by zytadam** [comment]
> please use pluginmaster_api9

Could you please specify a little on how to do that?

**Comment by zytadam** [comment]
> `https://raw.githubusercontent.com/Bluefissure/DalamudPlugins/Bluefissure/pluginmaster_api9.json `

well it works now, thank you for your replies!
