### ISSUE TITLE
6.0 update

### ISSUE THREAD

**Issue by AnzeG8** [Bluefissure/DoubleWeaver#6]
Hi o/

Any ETA on update for Endwalker release? I miss double weaving :)
Thanks for your work!

**Comment by Bluefissure** [comment]
I finished the MSQ yesterday to probably today is the day to update my plugins.
Or no later than this weekend if things changed a lot :)

**Comment by Bluefissure** [comment]
updated

**Comment by AnzeG8** [comment]
Hey, umm, did you commit the right thing? Double weaver still says outdated. Even after updating the repo link for API5 (which I'd recommend you add a link to instructions here since it was a pain to actually find).

**Comment by Bluefissure** [comment]
> Hey, umm, did you commit the right thing? Double weaver still says outdated. Even after updating the repo link for API5 (which I'd recommend you add a link to instructions here since it was a pain to actually find).

You can try to delete the third party link and add it again, iirc updating the url doesn't always work, so you probably are using the api4 branch.
The api5 branch is `https://raw.githubusercontent.com/Bluefissure/DalamudPlugins/Bluefissure/pluginmaster.json`

**Comment by AnzeG8** [comment]
> You can try to delete the third party link and add it again, iirc updating the url doesn't always work, so you probably are using the api4 branch. The api5 branch is `https://raw.githubusercontent.com/Bluefissure/DalamudPlugins/Bluefissure/pluginmaster.json`

Yea, had to uninstall double weaver, remove the repo, re-add it, re-install, now it's working. I guess it just kept the api4 version regardless of the repo link change. Thanks.
