### ISSUE TITLE
[Request]May you update the source code to Api 5.0?

### ISSUE THREAD

**Issue by 14ng3e** [Bluefissure/DoubleWeaver#8]
Sorry to bother you, I need to do some test on it,however the source code here is out-dated.I'd be appreciated if you could offer me the code I need!Many thanks!

**Comment by Bluefissure** [comment]
I'll push the code of api5 after getting home today.

**Comment by Bluefissure** [comment]
> Sorry to bother you, I need to do some test on it,however the source code here is out-dated.I'd be appreciated if you could offer me the code I need!Many thanks!

Just realized that there's no change from api4 to api5, besides the api version.

**Comment by 14ng3e** [comment]
> > Sorry to bother you, I need to do some test on it,however the source code here is out-dated.I'd be appreciated if you could offer me the code I need!Many thanks!
> 
> Just realized that there's no change from api4 to api5, besides the api version.
wow,thany you again for my silly request  : )
