### ISSUE TITLE
Is this wonderful plugin being updated to api6?

### ISSUE THREAD

**Issue by Spanglish1337** [Bluefissure/DoubleWeaver#9]
Good morning!

I have seen many many developers update their plugins to api6 6 to work with the new update. Is this plugin also being updated ? It is the best one so far that works amazing to let me double weave without ant issues or crashes.

**Comment by Bluefissure** [comment]
I'll update after some testing when I get home later today.

**Comment by Spanglish1337** [comment]
Thank you! I wish you the best of luck In your endeavors.

**Comment by Bluefissure** [comment]
Sorry for the late reply, my server got DDOS recently and I have to handle that.
It should be upgraded to api6 already.

**Comment by Spanglish1337** [comment]
Hello!

That's okay, no worries! 

I hope your server issue could be resolved, getting DDOS'd sounds scary! 

Thank you so much for the update, and I wish you the best on your endeavors and in your server.
